/*ERP 자원 투입 쿼리 */
INSERT INTO ERP_IF_RESOURCE_CKO112
(
 PLANT_CD
,PRODT_ORDER_NO
,RESULT_SEQ
,OPR_NO
,JOB_CD
,M_TYPE
,RESOURCE_CD
,WORK_DATE
,WORK_HOUR
,EMP_NO
,EMP_DATE
,EMP_HOUR
,INSRT_USER_ID
,INSRT_DT
,STATUS
,IF_RESULT
)
SELECT 
	  A.FacilityID 					--PLANT_CD
	, A.LotID  						--PRODT_ORDER_NO
	,'1' 							--RESULT_SEQ
	, A.Opr_CD  					--OPR_NO
	, A.SegmentID  					--JOB_CD
	, 'P' 							--M_TYPE
	, A.EquipmentID 				--RESOURCE_CD
	, CONVERT(DATETIME,'2021-12-30')--WORK_DATE
	, ISNULL(A.ActualTime ,0) 		--WORK_HOUR
	, CreateUser    				--EMP_NO
	, CONVERT(DATETIME,'2021-12-30')--EMP_DATE
	, ISNULL(A.ActualTime ,0) 		--EMP_HOUR
	, A.CreateUser 					--INSRT_USER_ID
	, CONVERT(DATETIME,'2021-12-30')--INSRT_DT
	,'C'							--STATUS
	,NULL							--IF_RESULT
FROM 
	LMSEGMENTRECORD AS A
WHERE 
	A.FacilityID  = 'PB1'
/*ERP원자재투입쿼리*/
INSERT INTO ERP_IF_CHILD_ISSUE_CKO112
(
	 PLANT_CD
	,PRODT_ORDER_NO
	,OPR_NO
	,CHILD_ITEM_CD
	,ISSUE_QTY
	,ISSUE_UNIT
	,ISSUE_QTY_KG
	,ISSUE_UNIT_KG
	,ISSUE_SL_CD
	,SCRAP_GUBUN
	,ISSUE_DT
	,LOT_NO
	,TRACKING_NO
	,ITEM_DOCUMENT_NO
	,DOCUMENT_YEAR
	,SEQ_NO
	,SUB_SEQ_NO
	,INSRT_USER_ID
	,INSRT_DT
	,STATUS
	
)

SELECT 
	 A.FacilityID 						AS PLANT_CD
	,A.LotID 							AS PRODT_ORDER_NO
	,A.Opr_CD 							AS OPR_NO
	,A.InputRawMaterial1MProductID 		AS CHILD_ITEM_CD
	,1									AS ISSUE_QTY
	,'EA'								AS ISSUE_UNIT
	,0									AS ISSUE_QTY_KG --PIS에 원자재 KG이 없다. 
	,'KG'								AS ISSUE_UNIT_KG
	,'*'  								AS ISSUE_SL_CD       
	,'N'								AS SCRAP_GUBUN
	, CONVERT(DATETIME,'2021-12-30') 	AS ISSUE_DT
	,A.InputRawMaterial1Lot 			AS LOT_NO
	,A.WorkOrderID 						AS TRACKING_NO
	,'*'								AS ITEM_DOCUMENT_NO
	,''									AS DOCUMENT_YEAR
	,1									AS SEQ_NO
	,'0'								AS SUB_SEQ_NO
	,A.CreateUser 						AS INSRT_USER_ID
	,CONVERT(DATETIME,'2021-12-30')		AS INSRT_DT
	,'C'								AS STATUS
FROM 
	LMSEGMENTRECORD  AS A
WHERE 
	A.FacilityID  = 'PB1'
	AND	A.InputRawMaterial1  IS NOT NULL
	AND A.SegmentID  ='110'	
	
/*ERP WO쿼리*/ 
INSERT INTO ERP_IF_WO_RECP_CKO112
(	
	PRODT_ORDER_NO ,
	RE_WORK_FLAG ,
	PLANT_CD ,
	ITEM_CD ,
	ORDER_QTY,
	ORDER_UNIT ,
	BASE_QTY ,
	BASE_UNIT ,
	PLAN_START_DT ,
	PLAN_COMPT_DT ,
	SL_CD,
	WC_CD,
	INSRT_USER_ID,
	INSRT_DT,
	ORDER_STATUS ,
	STATUS ,
	TRACKING_NO,
	IF_RESULT 
)	
SELECT
 LS.LotID 					--PRODT_ORDER_NO
 ,'N'						--RE_WORK_FLAG
 ,'PB1'						--PLANT_CD
 ,LS.ProductID				--ITEM_CD
 ,LS.UnitWeight				--ORDER_QTY
 ,'KG'						--ORDER_UNIT
 ,'1'						--BASE_QTY
 ,'EA'						--BASE_UNIT
 ,CONVERT(DATETIME,'2021-12-30') --PLAN_START_DT
 ,CONVERT(DATETIME,'2021-12-30') --PLAN_COMPT_DT
 ,'SFG11'--LW.SL_CD					--SL_CD  --가상으로 하나 잡는다. (본 반영시 수정하기)
 ,'PB110'					--WC_CD
 ,LS.CreateUser  			--INSRT_USER_ID
 ,LS.CreateTime				--INSRT_DT
 ,'ST'						--ORDER_STATUS
 ,'C'						--STATUS
 ,LW.TRACKING_NO			--TRACKING_NO
 ,NULL 						--IF_RESULT
FROM 
LMSEGMENTRECORD LS
LEFT JOIN LMWORKORDERINFO LW ON LS.Site = LW.Site AND LS.FacilityID = LW.FacilityID AND LS.WorkOrderID = LW.WorkOrderID
WHERE LS.SegmentID = '110'
AND LS.FacilityID = 'PB1'
AND LS.IsCompleted = 'Y'
;	



/*ERP실적 투입쿼리*/ 
INSERT INTO ERP_IF_WO_RESULT_CKO112
(
	PRODT_ORDER_NO,
	REPORT_DT,
	PLANT_CD,
	SHIFT_CD,
	ITEM_CD,
	PROD_QTY,
	PROD_UNIT,
	PROD_QTY_KG,
	PROD_UNIT_KG,
	RCPT_SL_CD,
	LOT_NO,
	TRACKING_NO,
	M_ITEM_CD,
	M_TRACKING_NO,
	M_LOT_NO,
	R_THICK,
	R_OUTDIA,
	R_WIDTH,
	PACK_NO,
	PACK_CNT,
	WC_CD,
	OPR_NO,
	JOB_CD,
	ROUT_ORDER,
	RESULT_SEQ,
	INSIDE_FLG,
	BP_CD,
	CUR_CD,
	SUBCONTRACT_PRC,
	CH_ITEM_CD,
	CH_BP_CD,
	CH_TRACKING_NO,	
	INSRT_USER_ID,
	INSRT_DT,
	STATUS,
	APPLY_FLAG,
	IF_RESULT
	
)
SELECT
	 A.LotID 					AS PRODT_ORDER_NO
	,CONVERT(DATETIME,'2021-12-30')	AS REPORT_DT
	,A.FacilityID 				AS PLANT_CD
	,A.ShiftID 					AS SHIFT_CD
	,A.ProductID 				AS ITEM_CD
	,1							AS PROD_QTY
	,'EA'						AS PROD_UNIT
	,A.UnitWeight 				AS PROD_QTY_KG
	,'KG'						AS PROD_UNIT_KG
	,'SFG11'--B.SL_CD 					AS RCPT_SL_CD 
	,A.LotID 					AS LOT_NO
	,A.WorkOrderID 				AS TRACKING_NO
	,CASE WHEN A.SegmentID  ='110' THEN A.InputRawMaterial1MProductID  ELSE '' END	AS M_ITEM_CD
	,B.Tracking_NO 				AS M_TRACKING_NO
	,CASE WHEN A.SegmentID  ='110' THEN A.InputRawMaterial1Lot  ELSE '' END			AS M_LOT_NO
	,CASE WHEN A.SegmentID  ='110' THEN CONVERT(float ,A.InputRawMaterial1Thickness)  ELSE 0 END 	  AS R_THICK
	,CASE WHEN A.SegmentID  ='110' THEN CONVERT(float ,A.InputRawMaterial1Length)  ELSE 0 END        AS R_OUTDIA
	,CASE WHEN A.SegmentID  ='110' THEN CONVERT(float ,A.InputRawMaterial1Width)  ELSE 0 END         AS R_WIDTH
	,''	AS PACK_NO
	,0 AS PACK_CNT
	,'PB'+ A.SegmentID  AS WC_CD
	,A.Opr_CD AS OPR_NO
	,A.SegmentID AS JOB_CD
	,CASE WHEN A.SegmentID  = '110' THEN 'F' WHEN A.SegmentID = '320' THEN 'L' ELSE 'I' END  AS ROUT_ORDER
	,1 AS RESULT_SEQ
	,CASE WHEN A.SegmentID  = '310' THEN  'N' WHEN A.SegmentID  = '270' THEN 'N' ELSE 'Y' END  AS INSIDE_FLG
	,CASE WHEN A.SegmentID  ='310'THEN  'DOM60364' WHEN A.SegmentID  = '270' THEN  'DOM62213' ELSE '' END AS BP_CD
	,'KRW' AS CUR_CD
	,0 AS SUBCONTRACT_PRC
	,'' AS CH_ITEM_CD
	,'' AS CH_BP_CD
	,'' AS CH_TRACKING_NO
	,A.CreateUser AS INSRT_USER_ID
	,CONVERT(DATETIME,'2021-12-30') AS INSRT_DT
	,'C' AS STATUS
	,NULL AS IF_RESULT
	
FROM 
	LMSEGMENTRECORD  AS A
	LEFT JOIN LMWORKORDERINFO  AS B 
	ON A.Site  = B.Site  AND A.FacilityID  = B.FacilityID  AND A.WorkOrderID  = B.WorkOrderID 
WHERE A.FacilityID  = 'PB1'
